// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLJ1hfCYJuDoORB0xs-taqhoHj0Kacs9I',
    appId: '1:299516139150:web:e557fe8481a5015c50dbdf',
    messagingSenderId: '299516139150',
    projectId: 'linkedin-f273c',
    authDomain: 'linkedin-f273c.firebaseapp.com',
    storageBucket: 'linkedin-f273c.firebasestorage.app',
    measurementId: 'G-TFC14VTZD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvlpd9TLLIqrhzbr6kvkidDYjspkxXSEM',
    appId: '1:299516139150:android:35694c18ed179d9b50dbdf',
    messagingSenderId: '299516139150',
    projectId: 'linkedin-f273c',
    storageBucket: 'linkedin-f273c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD00u8lJ9gROY-ghPTBJL1KLTHU9PEtowQ',
    appId: '1:299516139150:ios:a4dd67bf9519feaa50dbdf',
    messagingSenderId: '299516139150',
    projectId: 'linkedin-f273c',
    storageBucket: 'linkedin-f273c.firebasestorage.app',
    iosBundleId: 'com.justin.helloFlutter1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD00u8lJ9gROY-ghPTBJL1KLTHU9PEtowQ',
    appId: '1:299516139150:ios:a4dd67bf9519feaa50dbdf',
    messagingSenderId: '299516139150',
    projectId: 'linkedin-f273c',
    storageBucket: 'linkedin-f273c.firebasestorage.app',
    iosBundleId: 'com.justin.helloFlutter1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvFvUYlkVgY0g1QvqRQsgApoDnU3DaL90',
    appId: '1:299516139150:web:5eac21eb0546810e50dbdf',
    messagingSenderId: '299516139150',
    projectId: 'linkedin-f273c',
    authDomain: 'linkedin-f273c.firebaseapp.com',
    storageBucket: 'linkedin-f273c.firebasestorage.app',
    measurementId: 'G-R87M0BZES6',
  );
}
